export const GET_HOME_DATA="get_home_data"
export const GET_MOCK_CATEGORY="get_mock_category"
export const CET_MOCK_CATEGORY_LIST="get_mock_category_list"
export const GET_SEARCH_DATA = "get_search_data"
export const GET_SEARCH_RESULT = "get_search_result"